### ISSUE TITLE
magento 2.1 support

### ISSUE THREAD

**Issue by markus2810** [paymill/paymill-magento#43]
Are there any plans or road map to support magento 2.1?

**Comment by tschelabaumann** [comment]
Yes, we are currently working on updates on the current magento 1.x plugin (in 1-2 weeks) and a new plugin for magento 2.x (in 3-4 weeks).

**Comment by dmitry-fedyuk** [comment]
I have implemented **Paymill integration with Magento 2**: https://github.com/mage2pro/paymill  
It works with all Magento 2 versions: 2.0, 2.1, 2.2... etc.
![04](https://cloud.githubusercontent.com/assets/83204/22859835/322de590-f0fb-11e6-8ec6-78cefbcdb29d.png)
![03](https://cloud.githubusercontent.com/assets/83204/22859836/361a8140-f0fb-11e6-87b9-8b17db180471.png)
