### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by andreasemer** [paymill/paymill-magento#9]
It seems, that the Payment Options (CC and ELV) are not showing up, if a product (simple or virtual) have a recurring profile. 

Here is a Testcase:
- Enable the Paymill Payment Methods under System -> Conf. -> Payment Methods and enable "Recurring Payment"
- Create a Simple Product with "Enable Recurring Profile" enabled in the Backend
- Put this product in the the cart in the frontend
- Go to the checkout
- On the Payment Information Section the Paymill Payment Options are not showing up
- Remove the Recurring Profile Option in the Backend
- Go to the checkout
- The Paymill Payment Methods are showing up

Tested with Magento CE 1.7.0.2

**Comment by danielwill786** [comment]
Here is the module that supports recurring payments in Magento. You can set the downpayment percentage, maximum no of installments, recurring fee and much more. This module support following payment methods
1. Authorize.net
2. PayPal
3. Credit Card (saved)
4. Check / Money Order
5. Bank Transfer Payment
6. Cash On Delivery
For more details view demo here - http://bit.ly/1eTTW07

**Comment by patrickbaber** [comment]
Something new about the recurring payments in Magento? We need it too.
